# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Run Jekyll on Windows'
url:              http://einverne.github.io/run-jekyll-on-windows
baseurl:          /

github:
  repo:           https://github.com/juthilo/run-jekyll-on-windows

author:
  name:           'Julian Thilo'
  url:            https://twitter.com/juthilo
